config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts do 
  resources :comments
end

root "posts#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :posts

	has_attached_file :image, :styles => { :medium => "400x400>"}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :posts
   has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_comment, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!
	before_action :set_post

	def new
		@comment = Comment.new
	end

	def edit
	end

	def create
		@comment = Comment.new(comment_params)
		@comment.user_id = current_user.id
		@comment.post_id = @post.id

		if @comment.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def update
		@comment.update(comment_params)
	end

	def destroy
		@comment.destroy
	end

	private
		def set_comment
			@comment = Comment.find(params[:id])
		end

		def set_post
			@post = Post.find(params[:post_id])
		end

		def comment_params
			params.require(:comment).permit(:body)
		end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts = Post.all
	end

	def show
		@comments = Comment.where(post_id: @post.id)
	end

	def new
		@post = current_user.posts.build
	end

	def edit
		@post = Post.find(params[:id])
	end

	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	private

		def set_post
      @post = Post.find(params[:id])
    end

		def post_params
			params.require(:post).permit(:title,:body,:image)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@post, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <strong>Motivate:</strong><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back', post_path(@post) %>

app/views/comments/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', post_path(@post) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Motifit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "MotiFit", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "New Post", new_post_path, class: "active" %></li>
          <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %> </li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "active" %></li>
        <% end %>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class ="container">
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :multipart => true } do |f| %>
 
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <strong>Goal</strong><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <strong>Story</strong> <br>
    <%= f.text_area :body %>
  </p>
  <p>
    <strong>Image that describes your end goal</strong><br><br>
    <%= f.file_field :image %>
  </p>
 <br>
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/posts/edit.html.erb
<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% if user_signed_in? %>

<h1>
Quote of the Day
<blockquote id="qod-quote">
   ... loading ...
</blockquote>
<script src="http://quotesondesign.com/api/3.0/api-3.0.js" 
type="text/javascript" charset="utf-8"></script>
</h1>

<div class="row">
  <% @posts.each do |post| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag post.image.url(:medium), class: 'image'), post %>
      </div>
    </div>
  <% end %> 

<% else %>

<video autoplay  id="bgvid" loop muted>
  <!-- WCAG general accessibility recommendation is that media such as background video play through only once. Loop turned on for the purposes of illustration; if removed, the end of the video will fade in the same way created by pressing the "Pause" button  -->
<source src="http://artbees.net/themes/jupiter-demo/wp-content/uploads/2013/10/shutterstock_v3702740_4.m4v" type="video/mp4" type="video/mp4">
</video>
<div id="description">
<h1>MotiFit</h1>
<p>
<h3>Need an extra lift? Have our community help you plan it out! Everyone at MotiFit encourages each other to reach our fitness goals by sending advice and words of encouragement! Sign up today and motivate now!</h3>


</div>
<%end%>

</body>
</html>

app/views/posts/new.html.erb
 
<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="panel panel-default">
	<div class= "panel-body">
		<div class="row">
			<div class="col-md-4">
			<%= image_tag @post.image.url(:medium) %>
				<div class="table-responsive">
				<table class="table">
				<tbody>
					<tr>
						<td><strong>Goal:</strong></td>
						<td><%= @post.title %></td>
					</tr>
					<tr>
						<td><strong>Story:</strong></td>
						<td><%= @post.body %></td>
					</tr>
				</tbody>
		   </table>
		   <%= link_to 'Motivate!', new_post_comment_path(@post), class: "btn btn-danger" %>
       </div>
      </div>
      <div class="col-md-6 col-md-offset-2">
      	

      	<% if @comments.blank? %>
      	<h3> Send words of encouragement or advice!</h3>
      	<% else %>
      		<% @comments.each do |comment| %>
      			<div class="comments">
      				<p><%= comment.body %> </p>
      				</div>
      			<% end %>	
      			<% end %>	

      </div>
		</div>
	</div>
</div> 


<%= link_to 'Back', posts_path %>